### ISSUE TITLE
Since Fall Creators Update, AppIds need to be valid

### ISSUE THREAD

**Issue by Boddlnagg** [allenbenz/winrt-notification#1]
Before Windows 10 Fall Creators Update you could provide any string as AppId and it basically worked, but now it won't work anymore. This breaks the examples. See https://github.com/contextfree/winrt-rust/issues/44.

**Comment by allenbenz** [comment]
Well that is disappointing, was nice that it worked without a valid id for a while.

Looks like [other toast projects](https://github.com/Windos/BurntToast/blob/master/BurntToast/Public/New-BTAppId.ps1) have mechanisms to add an AppId to the registry.

I'll take a look into that over the weekend.

**Comment by Boddlnagg** [comment]
[This blogpost](https://king.geek.nz/2017/10/09/burnttoast-no-appid/) indicates that adding the AppId to the registry is not sufficient, which is why the BurntToast project switched to using the PowerShell AppId instead ...

**Comment by allenbenz** [comment]
So using `{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe` as the appId would make it work again?

This seems like something that would get broken again in a new update.

**Comment by Ciantic** [comment]
I think this is again broken, at least the simple example does not seem to produce anything. Windows 10 update 2004.

**Comment by mthelm85** [comment]
Simple example in the docs doesn't produce anything for me either. No error message, program executes, exits and no notification is shown.

**Comment by allenbenz** [comment]
Different issue.
For some reason a windows update made it sensitive to the application closing before the toast showed.
0.2.3 will add a 10ms wait after the show to prevent that from being an issue.

**Comment by allenbenz** [comment]
Closing the issue as using the powershell id has held for the last few years as a workaround to not having an installed application/proper app id.
