### ISSUE TITLE
Doesn't work on Win 8.1

### ISSUE THREAD

**Issue by Boscop** [allenbenz/winrt-notification#3]
Both examples do nothing :(
Any idea how to make it work?

**Comment by allenbenz** [comment]
I'll take a look at it on a win 8.1 vm this weekend.

**Comment by Boscop** [comment]
Thanks!

**Comment by allenbenz** [comment]
Okay so the issue is that I am using the ToastGeneric binding which is a windows 10 only thing.

Windows 8.1 only allowed fixed templates.
https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh761494(v=win.10)

So no short term fix here.
I'll think about how to work around this.

**Comment by allenbenz** [comment]
Alright, 0.2.0 should work with win 8.1.
At least it did on the 64-bit 8.1 VM.

If it doesn't let me know.
Note that 0.2.0 uses a later version of winrt (and by extension winapi)

**Comment by Boscop** [comment]
Yes, it works, thanks :)
It is a metro style notification bubble with blue background.
Btw, how to create a system tray bubble (the one with yellow/white background)?

**Comment by allenbenz** [comment]
That would use the Shell_NotifyIcon call.

It would be the way to get something like notifications in windows 7.

Some reading on it here:
https://msdn.microsoft.com/en-us/library/windows/desktop/ee330740(v=vs.85).aspx
https://softwareengineering.stackexchange.com/questions/222339/using-the-system-tray-notification-area-app-in-windows-7
