### ISSUE TITLE
Specify images using already loaded bytes rather than paths?

### ISSUE THREAD

**Issue by wez** [allenbenz/winrt-notification#6]
Is this feasible?  I have data that is referenced via `include_bytes!()` that I'd like to pass through.  The image doesn't live on the filesystem in the installed application.

Is is possible to pass a `data:image/png,base64,XXXXX=` URL rather than a path?

**Comment by allenbenz** [comment]
Unfortunately not, the URI toasts take is restricted to a few types.

[from the docs](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-image?redirectedfrom=MSDN#attributes):
```
The URI of the image source, using one of these protocol handlers:

http:// or https://
A web-based image.

ms-appx:///
An image included in the app package.

ms-appdata:///local/
An image saved to local storage.

file:///
A local image. (Supported only for desktop apps. This protocol cannot be used by UWP apps.)
```

**Comment by wez** [comment]
Thanks!  I suppose I'd better ship the image file with the app then :-)
