### ISSUE TITLE
Cannot find -lwinapi_ntdll

### ISSUE THREAD

**Issue by MoAlyousef** [allenbenz/winrt-notification#7]
Hello

Using the gnu toolchain (stable-x86_64-pc-windows-gnu version 1.48) currently fails to link. Reverting the 0.3 change in windows_check.rs to:
```rust
#[link(name = "ntdll")]
```
makes things work again.

P.S. Tried on msys2:
```
MINGW64_NT-10.0-19041 LAPTOP-1H9T8GEO 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
```

**Comment by allenbenz** [comment]
I'll be able to look at this over the weekend.
What does it take to get a working environment? I know this crate doesn't get past linking with the default mingw bundled with the gnu toolchain.

You've mentioned msys2, anything else? msys2-w32api-runtime? some other package? Do you need to set any environment variables?

**Comment by MoAlyousef** [comment]
Msys2 with some mingw-w64 binutils (that I need for building and running fltk apps):
```
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-cmake --needed
```
Rust and Cargo installed via Rustup, but choosing the stable-x86_64-pc-windows-gnu toolchain.
I keep my msys2 installation minimal. No manually set env variables. Only other packages installed are vim, curl, tar and git.
